name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run script
        run: |
          chmod +x script.sh
          ./script.sh

      - name: Check if successful
        id: check_success
        run: echo "::set-output name=success::true"
